// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingAi.Core.Data;

#nullable disable

namespace DataImporter.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260131024201_InitialCreate_CompositeKey")]
    partial class InitialCreate_CompositeKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TradingAi.Core.Models.FutureBarFull", b =>
                {
                    b.Property<string>("SymbolCode")
                        .HasMaxLength(9)
                        .HasColumnType("CHAR(9)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("Close")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<int>("ContractMonth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("DATE");

                    b.Property<decimal>("High")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<string>("IndexType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("CHAR(3)");

                    b.Property<decimal>("Low")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<int>("NumberOfTrade")
                        .HasColumnType("int");

                    b.Property<decimal>("Open")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<long>("RecordNo")
                        .HasColumnType("bigint");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("DATE");

                    b.Property<decimal>("VWAP")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("DATETIME");

                    b.HasKey("SymbolCode", "Timestamp");

                    b.HasIndex("ContractMonth");

                    b.ToTable("future_bars_full");
                });

            modelBuilder.Entity("TradingAi.Core.Models.OptionBarFull", b =>
                {
                    b.Property<string>("SymbolCode")
                        .HasMaxLength(9)
                        .HasColumnType("CHAR(9)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME");

                    b.Property<byte>("CashFuturesType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal>("Close")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<int>("ContractMonth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("DATE");

                    b.Property<decimal>("ExercisePrice")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<decimal>("High")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<decimal>("Low")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<int>("NumberOfTrade")
                        .HasColumnType("int");

                    b.Property<decimal>("Open")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<byte>("PutCallType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long>("RecordNo")
                        .HasColumnType("bigint");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("DATE");

                    b.Property<string>("UnderlyingCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("CHAR(4)");

                    b.Property<decimal>("VWAP")
                        .HasColumnType("DECIMAL(12, 4)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("DATETIME");

                    b.HasKey("SymbolCode", "Timestamp");

                    b.HasIndex("ContractMonth", "ExercisePrice", "PutCallType");

                    b.ToTable("option_bars_full");
                });
#pragma warning restore 612, 618
        }
    }
}
